### ISSUE TITLE
add silent mode to UI

### ISSUE THREAD

**Issue by archerzz** [IBM-Cloud/ibm-cloud-cli-sdk#201]
The UI should be able to be in silent mode, so as to suppress message output. We can provide a method to print regardlessly.

**Comment by duglin** [comment]
thanks for #209 however, I'd like to ask that we also add a `-v`/`--verbose` flag to turn on verbosity. AND, this will be controversial, to make `--quite` the default.

Traditionally, Unix-y commands are pretty quiet by default. And as such, if anything they provide a `-v` type of flag to get more output. Today IBM's guidelines propose this:

```
$ ic app create foo
Creating application 'foo'...
OK
Application 'foo' was created.
```

There are several problems with this being the default:
1 - We don't need to tell the user we're "Creating an app", they just asked for it - it provides no value
2 - `OK` is redundant with `Application ... was created`
3 - Neither `OK` nor `Application ... was created` are needed because no error was printed
4 - By being so verbose, by default, people are now forced to scan the output to see which lines are errors and which are meaningless noise they can skip. Most people do not do `echo $?` afterwards to see if the cmd worked or not. They just keep going unless there's an error message - which is now mixed in with a lot of other output users will not care about
5 - scripting this becomes really painful. If I want my script to be silent, except upon an error, I now need to redirect all output for ALL cmds to a file and then `cat` that file upon an error. W/o us being chatty I didn't need to do anything special at all
6 - using the output for a subsequent cmd  (e.g. piping it to another cmd) means I now have to grep-out these lines to get to the real info I care about

Yes people can get to the same net result with the new --quiet option, but the default should be the easy path. We shouldn't require people to do extra work to get the traditional Unix-y/Linux-y like experience.

To hammer the point... imagine this:
```
$ rm foo
Deleting file foo
OK
File foo was deleted.
```
How annoyed would people be? This is how our current design feels to me.
