### ISSUE TITLE
Sanitize any header that has X-Auth in it.

### ISSUE THREAD

**Issue by ashishth09** [IBM-Cloud/ibm-cloud-cli-sdk#79]
I see some users of the SDK need to set headers which have different suffixes to X-Auth-<suffix>.
Currently only Token as suffix is sanitized https://github.com/IBM-Bluemix/bluemix-cli-sdk/blob/master/bluemix/trace/trace.go#L92 . A more general regex is requested to take care of it
probably `(?m)^(X-Auth\S*): .*`

**Comment by archerzz** [comment]
@weieigao I think we can add a broader support for `X-Auth****` headers.

**Comment by archerzz** [comment]
@ashishth09 But to be honest, I think the backend service providers should re-consider the header names for authentication. `Authorization` header is quite flexible, since its value format is `<type> <credentials>`. They can easily define their own `<type>`, like http://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml
`X-Auth` is still OK. If next time there are even more patterns to support, we might reject the request.

**Comment by archerzz** [comment]
I just checked [AWS](http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-auth-using-authorization-header.html), and they are using `Authorization` header. Just the value is different, like:
```
Authorization: AWS4-HMAC-SHA256 
Credential=AKIAIOSFODNN7EXAMPLE/20130524/us-east-1/s3/aws4_request, 
SignedHeaders=host;range;x-amz-date,
Signature=fe5f80f77d5fa3beca038a248ff027d0445342fe2855ddc963176630326f1024
```

**Comment by weieigao** [comment]
Done.  
update trace logger's sanitize regular rexpression #97
